# Generated by Django 5.0.6 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_alter_complaint_latitude_alter_complaint_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
