# Generated by Django 5.0.6 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_alter_complaint_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="department_email_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="complaint",
            name="department_email_recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="complaint",
            name="department_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
